


bert_model_name: 'roberta-base'
model_save_path : 'save_model/test'
upstream : True
downstream_load_pkl : False

use_margin_rank_loss : False
use_classfier : False

max_query_length : 20
max_title_length : 60

use_additional_pdfeature : True
additional_pdfeature_locale : ['us', 'es']


batch_size : 32


num_labels : 1

device : 'cuda'


lr : 7e-6


epoch_num : 1

warmup_steps : 5000


margin : 0.00002

use_mixed_model : False


save_train_infer_score_as_data : True

