





# often used
bert_model_name: 'roberta-base'
model_save_path : 'save_model/test'
save_train_infer_score_as_data : False
updated_regression_label : {'E' : 1.0, 'S' : 0.1, 'C' : 0, 'I' : 0}
updated_classifier_label : {'E' : 0, 'S' : 1, 'C' : 2, 'I' : 2}
classifier_weights : [0.4115, 1.3260, 3.3296]
downstream_load_pkl : True
data_info_path : 'save_data/data_info_test'
target_fold : 0
batch_size : 32






# less used
use_margin_rank_loss : False
use_classfier : False
max_query_length : 20
max_title_length : 60
use_additional_pdfeature : True
additional_pdfeature_locale : ['us', 'es']
num_labels : 3
device : 'cuda'
lr : 7e-6
epoch_num : 1
warmup_steps : 5000
margin : 0.00002
use_mixed_model : False
margin_rank_sample_rate : 0.5


